version: "3.8"

services:

  db:
    image: postgres:15-alpine
    container_name: postgres_contabilidade
    restart: always
    environment:
      POSTGRES_USER: fernando
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: contabilidade_db
    ports:
      - "5432:5432"
    volumes:
 
      - ./pgdata:/var/lib/postgresql/data

  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_contabilidade
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
